os: linux
services: docker
env:
  global:
    - PROJECT_NAME: "Travis CI"
    - SCAN_MODE: baseline
    - API_URL: https://dev-api.soos.io/api/
    - TARGET_URL: https://soos-dast-juice-shop.herokuapp.com/#/
script:
  - docker run -it --rm soosio/dast --clientId=$SOOS_CLIENT_ID --apiKey=$SOOS_API_KEY --projectName=$PROJECT_NAME --scanMode=$SCAN_MODE --apiURL=$API_URL $TARGET_URL
